version: "2.27.0"
services:
  postgres:
    container_name: WebBookStorePostgresContainer
    image: postgres:latest
    environment:
      POSTGRES_DB: "WebBookStore"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:  
      - "5432:5432"

volumes:
  postgres-data: